# Generated by Django 2.2.4 on 2019-09-01 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'livreur',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_nom', models.CharField(max_length=100)),
                ('exp_tel', models.CharField(max_length=10)),
                ('dest_nom', models.TextField(max_length=100)),
                ('dest_tel', models.CharField(max_length=10)),
                ('dest_adresse', models.TextField(max_length=100)),
                ('dest_colis', models.TextField(max_length=250)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date enregistrement')),
                ('livreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Livreur')),
            ],
            options={
                'verbose_name': 'course',
                'ordering': ['date'],
            },
        ),
    ]
