# Generated by Django 2.2.4 on 2019-09-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dest_adresse',
            field=models.CharField(max_length=100, verbose_name='Adresse destination'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dest_colis',
            field=models.TextField(max_length=250, verbose_name='Description du service'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dest_nom',
            field=models.CharField(max_length=100, verbose_name='Nom destinataire'),
        ),
        migrations.AlterField(
            model_name='course',
            name='dest_tel',
            field=models.CharField(max_length=10, verbose_name='Téléphone destinataire'),
        ),
        migrations.AlterField(
            model_name='course',
            name='exp_nom',
            field=models.CharField(max_length=100, verbose_name='Nom expéditeur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='exp_tel',
            field=models.CharField(max_length=10, verbose_name='Téléphone expéditeur'),
        ),
    ]
